version: '2.1'

services:
  node:
    container_name: node
    build:
      context: .
      args:
        - ENVIRONMENT=development
    command: npm run develop
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - '3000:${PORT}'
    volumes:
      - .:/usr/src/app:cached

  postgres:
    container_name: database
    image: postgres:11.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_DATABASE
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 2s
      retries: 5
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  adminer:
    container_name: database-ui
    image: adminer:4
    logging:
      driver: none
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '8080:8080'
