on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: deploy-artefact
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@master
      - run: make docker-push
